"""add trades.fee_usdt

Revision ID: 8d5966c1eaed
Revises: 44c8e3a2b9f7
Create Date: 2026-08-25 19:55:09.518238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5966c1eaed'
down_revision: Union[str, Sequence[str], None] = '44c8e3a2b9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('fee_usdt', sa.Numeric(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'fee_usdt')
    # ### end Alembic commands ###
